
modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="post_mortem" #mandatory
version="${file.jarVersion}"
displayName="Post Mortem"

logoFile="examplemod.png"

credits="Babadzaki zaebal dark souls delat"

authors="Team Prometheus, nikgub_, BaronFonShish"

description='''
Post Mortem is a mod expanding on the concepts of death and afterlife

The mod adds many different weapons and tools as well as enemies
'''

[[dependencies.post_mortem]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.post_mortem]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
